### ISSUE TITLE
Migrate minimal event data and minimal session data over from cdptools

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#10]
## Use Case
*Please provide a use case to help us understand your request in context*

Standardize and version the acceptable data format we accept for pipelines with the pipeline code itself rather than scrapper side.

## Solution
*Please describe your ideal solution*

Migrate the work done by @isaacna on [cdptools](https://github.com/CouncilDataProject/cdptools/pull/159) to this repo.

Potentially change the name from `MinimalEventData` and `MinimalSessionData` to just `EventData` and `SessionData` as I think with the `Optional` keys, they are the full event data spec.

We should also make objects for `VoteData` and such, which are a part of the `Optional[List[MinutesItems]]`. Basically the entire data structure of all minimal data and optional data should be documented as the accepted data structure we accept for pipelines.

## Notes

This unfortunately will require a bit of copying the database ORM definitions unless we can think of a way to programmatically construct all of these models. I.E. run through the DB ORM definitions and created NamedTuples of every single model with the appropriate `Optional` tags. I think it's possible.

**Comment by isaacna** [comment]
Note to self, will also be adding an `Optional[List[EventMinutesItem]]`field to the `EventData`class

**Comment by isaacna** [comment]
Now that I think about it, using the existing `fireo` models might be difficult because some models have a bottom up reference, for example `Session.event_ref`. 

But if we want to output a single EventData object, we'll need to store `sessions` as part of the `EventData` object as a top down reference. Unless there's a workaround I'm missing, this would be a circular dependency. 

We could do something like typing `Event.sessions` as `List[str]` for document id references, and update them after the session documents are created? But at that point all the `EventData` wouldn't really be in a single object.

With this would it make more sense to create separate ingestion objects apart from the `fireo` models? There would have to be some logic that handles uploading the nested object data to the database in the proper order to not mess up references

**Comment by JacksonMaxfield** [comment]
Yea that's a good catch. I think it just makes sense to define a bunch of `NamedTuple` objects. Especially for documentation purposes having the ingestion structure really well documented would be nice.

Also note we can add / check / validate a bunch of the ingestion data based off of just primary keys where as the fireo models are "full objects" i.e. a `Person` model has name, email, etc, but in the ingestion, the dev _could_ add those but they _could_ also just add the person's name and we would take care of the rest because of primary key.
