### ISSUE TITLE
Try URL before creating / uploading Matterfile

### ISSUE THREAD

**Issue by liamphmurphy** [CouncilDataProject/cdp-backend#179]
### Feature Description

This feature (enhancement) would add a bit more resiliency to the creation of Matterfile's seen here: https://github.com/CouncilDataProject/cdp-backend/blob/2e472b92b5ef9cd49fc940bacfe1ed7e4f9cc496/cdp_backend/pipeline/event_gather_pipeline.py#L1444-L1452

Specifically, we want to check that the `supporting_file.uri` used in the creation of the Matterfile actually exists before creating / uploading the Matterfile.

### Use Case

Simply the use case here is to create better Matterfile data by ensuring that the URL's used exist.

### Solution

In the above linked code, before the call to `create_matter_file`, do the following:

1. Make a call to `try_url` (using the default resolve_func) to see if the URL exists.
2. IF exists, proceed with the creation / uploading of the Matterfile.
3. IF not exists, add `LookupError` as an exception to watch for in that loop, as `try_url` will raise that exception on errors.

### Alternatives

Let me know if any other options are better.

**Comment by liamphmurphy** [comment]
### Question

If the URL does exist but it turns out the call to `try_url` returns an `http` URL, should we have any special logic for that? Not familiar enough with the data yet to be sure, but I know that in some cases we have to host the specified resource if it is not HTTPS to workaround Firefox errors.

**Comment by JacksonMaxfield** [comment]
> In the above linked code, before the call to create_matter_file, do the following:
>
> Make a call to try_url (using the default resolve_func) to see if the URL exists.
> IF exists, proceed with the creation / uploading of the Matterfile.
> IF not exists, add LookupError as an exception to watch for in that loop, as try_url will raise that exception on errors.

This is perfect.

> Question
>
> If the URL does exist but it turns out the call to try_url returns an http URL, should we have any special logic for that? Not familiar enough with the data yet to be sure, but I know that in some cases we have to host the specified resource if it is not HTTPS to workaround Firefox errors.

Yes, if the returned URL is `http` we should store it. But for MatterFiles, MinutesItemFiles, etc, we can store those. We can store them because we aren't embedding the link or anything we are simply adding a link to the page which will open a new tab. Definitely some issues with Firefox but if we do it properly we should be able to solve that case too.

**Comment by liamphmurphy** [comment]
Thanks for the info @JacksonMaxfield! I just want to double check on the hosting bit... the class declaration for the SupportingFile mentions it is not stored in firestore: https://github.com/CouncilDataProject/cdp-backend/blob/951c227ddcc26df1c00c951c27595c5996c5e7cb/cdp_backend/pipeline/ingestion_models.py#L79 

Is that still accurate / does it pertain to this at all?

**Comment by JacksonMaxfield** [comment]
Great question! And I guess I didn't realize how deep in the weeds this issue was in the CDP infrastructure / pipeline. What you are looking at is our "ingestion models", the format of how  our pipeline accepts data. What we are storing is our [database models](https://github.com/CouncilDataProject/cdp-backend/blob/951c227ddcc26df1c00c951c27595c5996c5e7cb/cdp_backend/database/models.py#L323)

Regardless, those two things are connected, where you see a `SupportingFile` in the ingestion metadata, it gets converted into usually a `MatterFile` or `MinutesItemFile` for example.

But yes, these files aren't stored in our own file store, we just store a link (or the https or http URL) to the file in our database.

**Comment by liamphmurphy** [comment]
Apologies for the delay on getting this out, been working on it a bit this weekend and attempting to mock the `resource_exists` call in this test func https://github.com/CouncilDataProject/cdp-backend/blob/f77ca6d02099dcea71da8378ddf742951a4665a7/cdp_backend/tests/pipeline/test_event_gather_pipeline.py#L518 (so it doesn't actually perform HTTP requests) has been causing some problems. 

Will update if I have any further progress (hopefully in the form of a PR!).

**Comment by JacksonMaxfield** [comment]
I think you should be able to use:

```python
with mock.patch("cdp_backend.database.validators.resource_exists") as mocked_resource_exists:
    mocked_resource_exists.return_value = True
```

But I may be wrong...

**Comment by liamphmurphy** [comment]
> I think you should be able to use:
> 
> ```python
> with mock.patch("cdp_backend.database.validators.resource_exists") as mocked_resource_exists:
>     mocked_resource_exists.return_value = True
> ```
> 
> But I may be wrong...

I tried it with the parameterized patch, I'll try it with that way instead 👍
